// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBase.Models
{
    /// <summary>
    /// 
    /// </summary>
    public partial class Customer
    {
        public int? Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    }
}