// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBase.Models
{
    public partial class ProtectedZippedFiles
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] FileContent { get; set; }
        public DateTime CreatedDateTime { get; set; }
    }
}